const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Plugins.video,
		C3.Behaviors.Tween,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.advert,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{background_intro: 0},
	{loading_bar: 0},
	{loading_persen: 0},
	{tombol_belajar: 0},
	{tombol_belajar2: 0},
	{tombol_bermain: 0},
	{tombol_bermain2: 0},
	{tombol_info: 0},
	{tombol_keluar: 0},
	{tombol_tim: 0},
	{youtube: 0},
	{Browser: 0},
	{bg: 0},
	{frame: 0},
	{scrollbar: 0},
	{DragDrop: 0},
	{slider: 0},
	{bukaconstruct: 0},
	{bukaconstruct2: 0},
	{daftarakun: 0},
	{daftarakun2: 0},
	{interfaceconstruct: 0},
	{interfaceconstruct2: 0},
	{pausevideo: 0},
	{playvideo: 0},
	{simpanconstruct: 0},
	{simpanconstruct2: 0},
	{verifikasimail: 0},
	{verifikasimail2: 0},
	{Video1: 0},
	{video2: 0},
	{video3: 0},
	{video4: 0},
	{video5: 0},
	{BtnReset: 0},
	{txtAnswer: 0},
	{Tween: 0},
	{txtpercent: 0},
	{txtQ: 0},
	{txtQNum: 0},
	{txtQType: 0},
	{JSON: 0},
	{AJAX: 0},
	{index: 0},
	{Answer: 0},
	{Btn: 0},
	{txt1: 0},
	{correct: 0},
	{abjad: 0},
	{drop_huruf: 0},
	{Sine: 0},
	{hewan_soal: 0},
	{next: 0},
	{Particles: 0},
	{use: 0},
	{tempat: 0},
	{info: 0},
	{tim: 0},
	{TiledBackground: 0},
	{Text: 0},
	{par: 0},
	{Pin: 0},
	{rope: 0},
	{ScrollTo: 0},
	{focus: 0},
	{go: 0},
	{kamera: 0},
	{Physics: 0},
	{flour: 0},
	{flourGo: 0},
	{ClimbProgress: 0},
	{box: 0},
	{anchor: 0},
	{"4barChecking": 0},
	{"4barCounter": 0},
	{"4face": 0},
	{"4glass": 0},
	{"4ground": 0},
	{"4leftWall": 0},
	{"4rightWall": 0},
	{"4textScore": 0},
	{touching: 0},
	{"4tube": 0},
	{"4water": 0},
	{barChecking: 0},
	{barCounter: 0},
	{face: 0},
	{glass: 0},
	{leftWall: 0},
	{minigames: 0},
	{rightWall: 0},
	{tube: 0},
	{water: 0},
	{ground: 0},
	{textScore: 0},
	{background_app: 0},
	{tombol_kembali: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{textTimer: 0},
	{MobileAdvert: 0},
	{persen: 0},
	{slider_persen: 0},
	{konten_offset: 0},
	{scroll_ratio: 0},
	{QCount: 0},
	{QNum: 0},
	{QType: 0},
	{Q: 0},
	{Answers: 0},
	{CorrectAnswer: 0},
	{Clicked: 0},
	{TargetPercent: 0},
	{CorrectAnswered: 0},
	{timer: 0},
	{vNum: 0},
	{startX: 0},
	{startY: 0},
	{count: 0},
	{scoretowerbox: 0},
	{addBox: 0},
	{"4score": 0},
	{"4totalObjects": 0},
	{"4level": 0}
];

self.InstanceType = {
	background_intro: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ITiledBackgroundInstance {},
	loading_persen: class extends self.ITextInstance {},
	tombol_belajar: class extends self.ISpriteInstance {},
	tombol_belajar2: class extends self.ISpriteInstance {},
	tombol_bermain: class extends self.ISpriteInstance {},
	tombol_bermain2: class extends self.ISpriteInstance {},
	tombol_info: class extends self.ISpriteInstance {},
	tombol_keluar: class extends self.ISpriteInstance {},
	tombol_tim: class extends self.ISpriteInstance {},
	youtube: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bg: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	scrollbar: class extends self.ISpriteInstance {},
	slider: class extends self.ISpriteInstance {},
	bukaconstruct: class extends self.ISpriteInstance {},
	bukaconstruct2: class extends self.ISpriteInstance {},
	daftarakun: class extends self.ISpriteInstance {},
	daftarakun2: class extends self.ISpriteInstance {},
	interfaceconstruct: class extends self.ISpriteInstance {},
	interfaceconstruct2: class extends self.ISpriteInstance {},
	pausevideo: class extends self.ISpriteInstance {},
	playvideo: class extends self.ISpriteInstance {},
	simpanconstruct: class extends self.ISpriteInstance {},
	simpanconstruct2: class extends self.ISpriteInstance {},
	verifikasimail: class extends self.ISpriteInstance {},
	verifikasimail2: class extends self.ISpriteInstance {},
	Video1: class extends self.IWorldInstance {},
	video2: class extends self.IWorldInstance {},
	video3: class extends self.IWorldInstance {},
	video4: class extends self.IWorldInstance {},
	video5: class extends self.IWorldInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	txtAnswer: class extends self.ITextInstance {},
	txtpercent: class extends self.ITextInstance {},
	txtQ: class extends self.ITextInstance {},
	txtQNum: class extends self.ITextInstance {},
	txtQType: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	Btn: class extends self.IWorldInstance {},
	txt1: class extends self.ITextInstance {},
	abjad: class extends self.ISpriteInstance {},
	drop_huruf: class extends self.ISpriteInstance {},
	hewan_soal: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	tempat: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	tim: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	par: class extends self.ISpriteInstance {},
	rope: class extends self.ISpriteInstance {},
	focus: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	kamera: class extends self.ISpriteInstance {},
	flour: class extends self.ISpriteInstance {},
	flourGo: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	anchor: class extends self.ISpriteInstance {},
	_4barChecking: class extends self.ISpriteInstance {},
	_4barCounter: class extends self.ISpriteInstance {},
	_4face: class extends self.ISpriteInstance {},
	_4glass: class extends self.ISpriteInstance {},
	_4ground: class extends self.ISpriteInstance {},
	_4leftWall: class extends self.ISpriteInstance {},
	_4rightWall: class extends self.ISpriteInstance {},
	_4textScore: class extends self.ITextInstance {},
	_4tube: class extends self.ISpriteInstance {},
	_4water: class extends self.ISpriteInstance {},
	barChecking: class extends self.ISpriteInstance {},
	barCounter: class extends self.ISpriteInstance {},
	face: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	leftWall: class extends self.ISpriteInstance {},
	minigames: class extends self.ISpriteInstance {},
	rightWall: class extends self.ISpriteInstance {},
	tube: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	textScore: class extends self.ITextInstance {},
	background_app: class extends self.ISpriteInstance {},
	tombol_kembali: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	textTimer: class extends self.ITextInstance {},
	MobileAdvert: class extends self.IInstance {}
}